### ISSUE TITLE
stormforge cli doesn't allow config set for parameters that have periods in the name

### ISSUE THREAD

**Issue by liko9** [thestormforge/optimize-controller#464]
When trying to run `stormforge config set controller.k8s.testing.stormforge.io.env.DEBUG true`, I receive an error "`Error: unknown config property: controller.k8s.testing.stormforge.io.env.DEBUG`" - which I believe is due to the context having periods in the name.  My other contexts are able to set the DEBUG variable to the string "true"

**Comment by jgustie** [comment]
Correct, `stormforge config set` relies on "." delimited segments for the key names; so there is no mechanism for addressing YAML field names that contain ".". The current configuration commands are being replaced in the next major version and this will be addressed then. In the meantime, #466 will allow you to use the context name (e.g. "default") in place of the controller name to address the appropriate configuration settings.
